fail_fast: true
repos:
- repo: local
  hooks:
  - id: format
    name: Blacken & ISort
    entry: ["black .", "isort .", "black ."]
    pass_filenames: False
    language: system

  - id: fab-render-readme
    name: Render README
    entry: fab render-readme
    pass_filenames: False
    language: system
