fail_fast: true
repos:
- repo: local
  hooks:
  - id: format
    name: Format
    entry: fab misc.format --check
    pass_filenames: False
    language: system

  - id: render-readme
    name: Render README
    entry: fab misc.render-readme
    pass_filenames: False
    language: system

  - id: clear-metadata
    name: Clear Metadata
    entry: fab misc.clear-metadata
    pass_filenames: False
    language: system
