from pathlib import Path

SERVICES_REMOTE_ROOT = "/srv"
COMPOSE_REMOTE_ROOT = "~"
COMPOSE_FILE = "docker-compose.yml"
HOMER_REMOTE_FILE = "config.yml"
TRANSMISSION_REMOTE_FILE = "settings.json"
DCP = f"docker-compose -f {COMPOSE_REMOTE_ROOT}/{COMPOSE_FILE}"
MEDIA_REMOTE_ROOT = "/mnt/mybook/srv/media/"

LOCAL_ROOT = "."
BACKUP_DIR = "backup"
DOCKERFILE_DIR = "dockerfiles"
PROFILE_FILE = ".profile"
SERVICES_FILE = "services.yml"
HOMER_FILE = "homer-config.yml"
TRANSMISSION_FILE = "transmission-config.yml"
SERVICES_PATH = Path(LOCAL_ROOT) / SERVICES_FILE
COMPOSE_PATH = Path(LOCAL_ROOT) / COMPOSE_FILE
PROFILE_PATH = Path(LOCAL_ROOT) / PROFILE_FILE
HOMER_PATH = Path(LOCAL_ROOT) / HOMER_FILE
TRANSMISSION_PATH = Path(LOCAL_ROOT) / TRANSMISSION_FILE
BACKUP_PATH = Path(LOCAL_ROOT) / BACKUP_DIR
DOCKERFILE_PATH = Path(LOCAL_ROOT) / DOCKERFILE_DIR
